### ISSUE TITLE
Support Play 2.6 with Scala 2.11

### ISSUE THREAD

**Issue by tartakynov** [leanovate/swagger-check#15]
I am using swagger-check in one of my projects, but as soon as I migrated it to Play 2.6, swagger-check stopped working. I think the reason is because swagger-check only supports Play 2.6 with Scala 2.12 whereas my project has a few dependencies which are not available for Scala 2.12 yet, so I have to stay with Scala 2.11. 

I just want to know if you have plans to support of Play 2.6 with Scala 2.11 so I could adjust my plans, or I could help you with support of Play 2.6. I believe the original idea with the separate modules was to deal with this kind of situation but I don't quite understand where it should go now

**Comment by untoldwind** [comment]
So far I always combined a migration to play 2.6 with a migration to 2.12, so I did not had much examples. But I can take a look, the codebase should not have any 2.12 specifics, so it should be mostly some twiddling with version numbers

**Comment by tartakynov** [comment]
There's a conditional dependency to play-test, for Scala 2.11 swagger-check-core uses play-test 2.5. 

The problem is that play-test 2.5 is not compatible with play 2.6, so swagger-check fails to run due to some weird internal errors

**Comment by untoldwind** [comment]
That's more or less what I meant.
I've split up the code into a legacy-branch and a new master which is only compatible with Play 2.6 (for Scala 2.11, 2.12)
Probably there is still a bit of cleanup necessary, but I planing to release that as 1.0.0

**Comment by untoldwind** [comment]
1.0.0 is out and should work with 2.6 with both scala versions.
Otherwise just reopen the issue
